### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by mihir0109** [tizisdeepan/VideoEditor#3]
Getting below error:

jetified-videoeditor-1.0.8\res\values\values.xml:15:5-51: AAPT: error: resource dimen/_10sdp (aka com.app.xyz:dimen/_10sdp) not found.

**Comment by Abdugani-Temirbaev** [comment]
try to create **dimens.xml** and add

`    <dimen name="_15sdp">15sp</dimen>
    <dimen name="_14sdp">14sp</dimen>
    <dimen name="_13sdp">13sp</dimen>
    <dimen name="_12sdp">12sp</dimen>
    <dimen name="_11sdp">11sp</dimen>
    <dimen name="_10sdp">10sp</dimen>
    <dimen name="_30sdp">30sp</dimen>
    <dimen name="_9sdp">9sp</dimen>
    <dimen name="_3sdp">3sp</dimen>
    <dimen name="_4sdp">4sp</dimen>
    <dimen name="_5sdp">5sp</dimen>
    <dimen name="_50sdp">50sp</dimen>
`

**Comment by tizisdeepan** [comment]
Try adding resources from https://github.com/intuit/sdp
