### ISSUE TITLE
Minimum duration is not working

### ISSUE THREAD

**Issue by iamkdblue** [tizisdeepan/VideoEditor#4]
Thanks for this great project.

if i set minimum duration 10 sec and move bar towards each other, it collapse, max duration working fine.

**Comment by farislivemaker** [comment]
> Thanks for this great project.
> 
> if i set minimum duration 10 sec and move bar towards each other, it collapse, max duration working fine.

Yeah its not working.

**Comment by tizisdeepan** [comment]
For now, the workaround would be manually checking the min duration as there is a bug with the min duration code.
