### ISSUE TITLE
Getting Resource Linking failed

### ISSUE THREAD

**Issue by 7994** [tizisdeepan/VideoEditor#6]
Android resource linking failed

> .gradle\caches\transforms-2\files-2.1\440c0d5adabe4db2640b6ca8533c3582\jetified-videoeditor-1.0.8\res\values\values.xml:15:5-51: AAPT: error: resource dimen/_10sdp (aka com.example.practical:dimen/_10sdp) not found.

**Comment by tizisdeepan** [comment]
Import sdp resources to fix this
https://github.com/intuit/sdp
